<div class="anchoPantalla" style="position:relative">
				<ul id="nav">
					<li class="current">NOSOTROS</li>
					<li><a href="">&Uacute;NETE</a></li>
					<li id="btn_trabajo"><a href="">TRABAJO</a></li>
					<li id="btn_beneficios"><a href="">BENEFICIOS</a></li>
					<li id="btn_fundacion"><a href="">FUNDACI&Oacute;N</a></li>
				</ul>
				
				<div id="beneficiosNav">
					<ul id="navBen">
					<li><a href="">PROTECCI&Oacute;N DE SALUD Y VIDA</a></li>
					<li><a href="">ASISTENCIAS</a></li>
					<li><a href="">SEGURIDAD</a></li>
					<li><a href="">APOYO A EXTRANJEROS</a></li>
					<li><a href="">FOMENTO AL AHORRO Y RETIRO</a></li>
					<li><a href="">ASESOR&Iacute;A EN CR&Eacute;DITOS</a></li>
					<li><a href="">OPORTUNIDADES DE TRABAJO</a></li>
					<li><a href="">COMPROBANTES LABORALES</a></li>
					<li><a href="">CAPACITACI&Oacute;N Y DESARROLLO</a></li>
					<li><a href="">APOYO A EMPRENDEDORES</a></li>
					<li><a href="">APOYO A MADRES SOLTERAS</a></li>
					<li><a href="">APOYO CONTRA ADICCIONES</a></li>
					<li><a href="">FOMENTO SALUD Y DEPORTE</a></li>
				</ul>
				</div>

			</div>